version: '3.8'
services:
  db:
    image: postgres
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: db_recipe
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
      build: .
      container_name: web
      command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
        interval: 10s
        timeout: 5s
        retries: 5
  import:
    build: .
    command: python import_recipes.py
    volumes:
      - .:/code
    depends_on:
      web:
        condition: service_healthy
volumes:
  pgdata: